### ISSUE TITLE
Plurals not localizing correctly on iOS in 0.17.2

### ISSUE THREAD

**Issue by colintheshots-meetup** [icerockdev/moko-resources#261] opened 2021-12-02 19:58 UTC
In our shared KMM code, we tried both:

```
        fun dateString(numDays: Int): StringDesc {
            return when {
                numDays == 0 -> MR.strings.event_create_rsvp_start_date_today.format(dateToShow)
                numDays < 7 -> MR.plurals.rsvp_days_before.format(numDays, numDays, dateToShow)
                else -> MR.plurals.rsvp_weeks_before.format(numDays / 7, numDays / 7, dateToShow)
            }
        }
```

as well as the other format:

```
        fun dateString(numDays: Int): StringDesc {
            return when {
                numDays == 0 -> StringDesc.ResourceFormatted(MR.strings.event_create_rsvp_end_date_day_of_event, dateToShow)
                numDays < 7 -> StringDesc.PluralFormatted(MR.plurals.rsvp_days_before, numDays, numDays, dateToShow)
                else -> StringDesc.PluralFormatted(MR.plurals.rsvp_weeks_before, numDays / 7, numDays / 7, dateToShow)
            }
        }
```

In both instances, Android works fine by calling `dateString(it).toString(LocalContext.current)` but iOS simply returns the string's key as a String when calling `dateString(it).localized()`.

We noticed that `PluralFormattedStringDesc` doesn't exist in the shared framework created for iOS, but `ResourceFormattedStringDesc` does with its `localized()` function. This makes it seem like the library isn't including enough resources to properly localize the plurals. I'm surprised though that it doesn't crash due to missing the required function.

Looking at Shared.h, I'm seeing this return type for the StringDesc that could be either a formatted plural or a formatted resource.

```
- (id<SharedResourcesStringDesc>)dateStringNumDays:(int32_t)numDays __attribute__((swift_name("dateString(numDays:)")));

```

Does one need to explicitly always return the most specific of either a StringDesc, a PluralStringDesc, or a PluralFormattedStringDesc for iOS to localize plurals?

**Comment by colintheshots-meetup** [comment] 2021-12-02 20:58
Changing the return type of `dateString(numDays)` to `PluralFormattedStringDesc` does not appear to workaround the bug. The `.localized()` function is still returning only the id of the plural.

**Comment by colintheshots-meetup** [comment] 2021-12-02 21:32
It looks like the issue is iOS cannot handle positional arguments: %1$s %2$d ... etc. If I remove use simple format specifiers like %s and %d, then the problem goes away.

**Comment by Alex009** [comment] 2022-01-14 11:46
@colintheshots-meetup hi!

to see `PluralFormattedStringDesc` from Swift side you should add `moko-resources` to `export` dependencies of `framework`. 
https://kotlinlang.org/docs/mpp-build-native-binaries.html#export-dependencies-to-binaries here description how to do it

when you call `localized` function you can got key instead of value in case when you use static framework and not configure build phase with resources copy.

https://github.com/icerockdev/moko-resources#static-kotlin-frameworks-support here described how to configure static framework.

i can't reproduce your issue. so for now i close it, but feel free to reopen - please reproduce problem in sample project and publish it. in this case i will fix it

**Closed by Alex009** 2022-01-14 11:46 UTC
Labels: bug
