### ISSUE TITLE
Task X  uses this output of task '.... generateMRcommonMain' without declaring an explicit or implicit dependency.

### ISSUE THREAD

**Issue by mustafaozhan** [icerockdev/moko-resources#421] opened 2023-02-24 10:48 UTC
Similar to https://github.com/icerockdev/moko-resources/issues/375

but I created this one since it happens to manually added tasks into the project. Who knows, maybe the fix for above issue will fix this one too.

I have in my root gradle this detekt setup, it is the current [working/suggested](https://github.com/detekt/detekt/issues/5611#issuecomment-1365505710) way for KMP apps:
```
allprojects {
    apply(plugin = rootProject.libs.plugins.detekt.get().pluginId).also {
        detekt {
            buildUponDefaultConfig = true
            allRules = true
            parallel = true
            config = files("${rootProject.projectDir}/detekt.yml")
        }
        tasks.withType<Detekt> {
            setSource(files(project.projectDir))
            exclude("**/build/**")
            exclude {
                it.file.relativeTo(projectDir).startsWith(project.buildDir.relativeTo(projectDir))
            }
        }

        tasks.register("detektAll") {
            dependsOn(tasks.withType<Detekt>())
        }

        dependencies {
            detektPlugins(rootProject.libs.common.detektFormatting)
        }
    }
}
```

After Updating Gradle to 8.0 my build start failing with below error:
```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
A problem was found with the configuration of task ':client:core:res:detektMetadataCommonMain' (type 'Detekt').
  - Gradle detected a problem with the following location: '/Users/mustafa.ozhan/Projects/Oztechan/CurrencyConverterCalculator/CCC/client/core/res/build/generated/moko/commonMain/src'.
    
    Reason: Task ':client:core:res:detektMetadataCommonMain' uses this output of task ':client:core:res:generateMRcommonMain' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':client:core:res:generateMRcommonMain' as an input of ':client:core:res:detektMetadataCommonMain'.
      2. Declare an explicit dependency on ':client:core:res:generateMRcommonMain' from ':client:core:res:detektMetadataCommonMain' using Task#dependsOn.
      3. Declare an explicit dependency on ':client:core:res:generateMRcommonMain' from ':client:core:res:detektMetadataCommonMain' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem was found with the configuration of task ':client:core:res:detektMetadataMain' (type 'Detekt').
  - Gradle detected a problem with the following location: '/Users/mustafa.ozhan/Projects/Oztechan/CurrencyConverterCalculator/CCC/client/core/res/build/generated/moko/commonMain/src'.
    
    Reason: Task ':client:core:res:detektMetadataMain' uses this output of task ':client:core:res:generateMRcommonMain' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':client:core:res:generateMRcommonMain' as an input of ':client:core:res:detektMetadataMain'.
      2. Declare an explicit dependency on ':client:core:res:generateMRcommonMain' from ':client:core:res:detektMetadataMain' using Task#dependsOn.
      3. Declare an explicit dependency on ':client:core:res:generateMRcommonMain' from ':client:core:res:detektMetadataMain' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
==============================================================================

* Get more help at https://help.gradle.org
```

I use this block as a workaround in the gradle file where moko resources used for now:
```
tasks.withType<Detekt> {
    dependsOn("generateMRcommonMain")
}
```

**Comment by Alex009** [comment] 2023-03-27 05:46
same problem with desktop target on gradle 8.
workaround for desktop:
```
tasks.matching { it.name == "desktopProcessResources" }.configureEach {
    dependsOn(tasks.matching { it.name == "generateMRdesktopMain" })
}
```

**Comment by Alex009** [comment] 2023-04-12 07:26
will be released in 0.21.2

**Closed by Alex009** 2023-04-12 07:26 UTC
Labels: bug

**Comment by Siddounet** [comment] 2023-04-25 16:08
Not sure the issue is fully fixed.
I tested 0.21.2 & 0.22.0, and it's not working with ktlint (but seems OK with detekt)

```
> Task :shared:runKtlintCheckOverCommonMainSourceSet FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':shared:runKtlintCheckOverCommonMainSourceSet' (type 'KtLintCheckTask').
  - Gradle detected a problem with the following location: '/Users/bastien.coutable/git_repos/ekDevkmm/shared/build/generated/moko/commonMain/src'.
    
    Reason: Task ':shared:runKtlintCheckOverCommonMainSourceSet' uses this output of task ':shared:generateMRcommonMain' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':shared:generateMRcommonMain' as an input of ':shared:runKtlintCheckOverCommonMainSourceSet'.
      2. Declare an explicit dependency on ':shared:generateMRcommonMain' from ':shared:runKtlintCheckOverCommonMainSourceSet' using Task#dependsOn.
      3. Declare an explicit dependency on ':shared:generateMRcommonMain' from ':shared:runKtlintCheckOverCommonMainSourceSet' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```
Is this related to the issue ?
Thanks,
Bastien

**Comment by blonsky95** [comment] 2023-08-15 14:45
Same here:
AGP version: 8.0.2
Different errors but same issue
```
Reason: Task ':shared:syncComposeResourcesForIos' uses this output of task ':shared:generateMRiosX64Main' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':shared:generateMRiosX64Main' as an input of ':shared:syncComposeResourcesForIos'.
      2. Declare an explicit dependency on ':shared:generateMRiosX64Main' from ':shared:syncComposeResourcesForIos' using Task#dependsOn.
      3. Declare an explicit dependency on ':shared:generateMRiosX64Main' from ':shared:syncComposeResourcesForIos' using Task#mustRunAfter.
    
    Please refer to https://docs.gradle.org/8.0/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: '/Users/pablotrescoligarcia/AndroidStudioProjects/PocketAthleticsKMM/shared/build/generated/moko/commonMain/res'.
    
    Reason: Task ':shared:syncComposeResourcesForIos' uses this output of task ':shared:generateMRcommonMain' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':shared:generateMRcommonMain' as an input of ':shared:syncComposeResourcesForIos'.
      2. Declare an explicit dependency on ':shared:generateMRcommonMain' from ':shared:syncComposeResourcesForIos' using Task#dependsOn.
      3. Declare an explicit dependency on ':shared:generateMRcommonMain' from ':shared:syncComposeResourcesForIos' using Task#mustRunAfter.
```
      
fixed with @OSemenovBoyarka solution:
```
afterEvaluate {
  tasks.named("syncComposeResourcesForIos") {
    dependsOn(":shared:generateMRiosX64Main",":shared:generateMRcommonMain")
  }
}
```
